-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2OW8pDyVT+wqUdAc
FFwpkeHbOEdv7+pibOAlWCHjFnigCgYIKoZIzj0DAQehRANCAAQRdU30MFjeuzzi
zvdeuc7vKcmDhcpMyIxWWlYHkHCouVrkD0gmDr8Ogl8MxDTQnfKLGunwEaik5lo4
m/ZvWfna
-----END PRIVATE KEY-----