lane :download_udids do
    firebase_app_distribution_get_udids(
        project_number: "763106904719",
        output_file: "udids.csv"
    )
end

lane :add_new_devices do
    register_devices(devices_file: "udids.csv") 
end 