// leave off @2x/@3x
const images = {
	icnBigDown: require("./images/icn_big_down.png"),
	icnBigLeft: require("./images/icn_big_left.png"),
	icnBigUp: require("./images/icn_big_up.png"),
	icnChatAlertOff: require("./images/icn_chat_alert_off.png"),
	icnChatAlertOn: require("./images/icn_chat_alert_on.png"),
	icnChatOptions: require("./images/icn_chat_options.png"),
	icnChatUrgent: require("./images/icn_chat_urgent.png"),
	icnChatSend: require("./images/icn_chat_send.png"),
	icnMenuChat: require("./images/icn_menu_chat.png"),
	icnMenuClose: require("./images/icn_menu_close.png"),
	icnMenuHome: require("./images/icn_menu_home.png"),
	icnMenuResources: require("./images/icn_menu_resources.png"),
	icnMenuSettings: require("./images/icn_menu_settings.png"),
	icnMenu: require("./images/icn_menu.png"),
	icnMessages: require("./images/icn_messages.png"),
	icnSmRightGray: require("./images/icn_sm_right_gray.png"),
	icnToggleOff: require("./images/icn_toggle_off.png"),
	icnToggleOn: require("./images/icn_toggle_on.png"),
	launchBackground: require("./images/launch_background.png"),
	logoWhite: require("./images/logo_white.png"),
	logoBig: require("./images/logo-big.png"),
	onboardingAccess: require("./images/onboarding-access.png"),
	onboardingChat: require("./images/onboarding-chat.png"),
	onboardingNotifications: require("./images/onboarding-notifications.png"),
	office: require("./images/office.png"),
	icnFaceID: require("./images/icn_faceid.png"),
	icnTouchID: require("./images/icn_touchid.png"),
	icnCamera: require("./images/icn_camera.png"),
	icnImportant: require("./images/icn_important.png"),
	icnPhoto: require("./images/icn_photo.png"),
	icnSend: require("./images/icn_send.png"),
}

export default images
